---
- name: Развертывание Простого Flask-сайта
  hosts: web_servers
  become: yes
  gather_facts: false # <-- ДОБАВЬТЕ ЭТУ СТРОКУ
  tasks:
    - name: Обновить системные пакеты
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        # ... остальные задачи вашего плейбука ...
