---
- name: Развертывание Простого Flask-сайта
  hosts: web_servers # Группа серверов, на которую будем разворачивать
  become: yes # Выполнять все задачи с правами администратора (через sudo)

  # Переменные, которые можно легко изменить
  vars:
    project_root_path: /opt/my_simple_website # Куда скопировать сайт на Slave ВМ
    nginx_listen_port: 80 # Порт, на котором Nginx будет слушать входящие запросы (обычно 80 для HTTP)
    flask_app_port: 5000 # Порт, на котором Flask-приложение будет слушать
    # Путь к нашему проекту на AWX-Master ВМ.
    # AWX будет копировать файлы из этой папки на Slave.
    local_source_code_path: "/home/user/my_flask_project"

  tasks:
    - name: "БЛОК 1: Проверка и Остановка Существующих Сервисов"
      block:
        - name: Проверить, запущен ли Flask-сайт (поиск процесса)
          ansible.builtin.shell: "pgrep -f 'python {{ project_root_path }}/app.py'"
          register: flask_process_check # Сохраняем результат выполнения команды
          ignore_errors: yes # Если процесс не найден, это не ошибка для нас
          changed_when: false # Эта задача ничего не меняет на системе

        - name: Отключить Flask-сайт, если он был запущен
          ansible.builtin.command: "pkill -f 'python {{ project_root_path }}/app.py'"
          when: flask_process_check.rc == 0 # Выполнять только если предыдущая команда нашла процесс (код возврата 0)
          ignore_errors: yes # Игнорируем ошибку, если вдруг процесс уже завершился

        - name: Проверить, установлен ли Nginx
          ansible.builtin.package:
            name: nginx
            state: present # Проверяем, что пакет Nginx установлен
          check_mode: yes # ОЧЕНЬ ВАЖНО: Режим проверки, ничего не устанавливает, только говорит, установлен ли
          register: nginx_installed_check # Сохраняем результат проверки
          changed_when: false # Эта задача ничего не меняет

        - name: Выключить Nginx, если он установлен и активен
          ansible.builtin.systemd:
            name: nginx # Имя службы Nginx
            state: stopped # Остановить службу
            enabled: no # Отключить из автозапуска при загрузке системы
          when: nginx_installed_check.changed # Выполнять, если Nginx был обнаружен как "установленный"
          ignore_errors: yes # Игнорируем ошибку, если Nginx не был запущен

    - name: "БЛОК 2: Загрузка Проекта, Зависимостей и Настройка Nginx"
      block:
        - name: Создать корневую директорию для проекта на Slave ВМ
          ansible.builtin.file:
            path: "{{ project_root_path }}" # Путь, куда скопируем сайт
            state: directory # Указываем, что это директория
            mode: '0755' # Права доступа (rwxr-xr-x)

        - name: Скопировать файлы проекта с AWX-Master на Slave ВМ
          ansible.builtin.copy:
            src: "{{ local_source_code_path }}/" # Источник: ваша папка на AWX-Master
            dest: "{{ project_root_path }}" # Куда копировать на Slave
            owner: root # Владелец файлов
            group: root # Группа владельца
            mode: '0644' # Права доступа для скопированных файлов (rw-r--r--)
            # Папки будут наследовать права от project_root_path

        - name: Установить Python3 и pip3 (менеджер пакетов Python)
          ansible.builtin.package:
            name:
              - python3
              - python3-pip
            state: present # Убедиться, что они установлены

        - name: Установить зависимости Python из requirements.txt
          ansible.builtin.pip:
            requirements: "{{ project_root_path }}/requirements.txt" # Путь к файлу зависимостей на Slave
            executable: pip3 # Используем pip3

        - name: Установить Nginx
          ansible.builtin.package:
            name: nginx
            state: present # Убедиться, что Nginx установлен

        - name: Настроить Nginx как обратный прокси для Flask-приложения
          ansible.builtin.template:
            src: nginx_site.conf.j2 # Имя файла шаблона на AWX-Master (см. ниже)
            dest: /etc/nginx/sites-available/default # Куда скопировать на Slave (для Ubuntu/Debian)
            owner: root
            group: root
            mode: '0644'
          notify: Restart Nginx # Уведомить handler о необходимости перезапуска Nginx

        - name: Удалить ссылку на дефолтный конфиг Nginx (для Ubuntu/Debian)
          ansible.builtin.file:
            path: /etc/nginx/sites-enabled/default
            state: absent # Удалить, если существует
          notify: Restart Nginx # Чтобы Nginx подхватил изменения

        - name: Создать символическую ссылку на наш конфиг Nginx (включить его)
          ansible.builtin.file:
            src: /etc/nginx/sites-available/default
            dest: /etc/nginx/sites-enabled/default
            state: link # Создать символическую ссылку
            force: yes # Перезаписать, если ссылка уже существует
          notify: Restart Nginx # Перезапустить Nginx для применения изменений

    - name: "БЛОК 3: Старт Проекта, Nginx и Финальная Проверка"
      block:
        - name: Создать systemd сервис-файл для Flask-приложения
          ansible.builtin.template:
            src: flask_app.service.j2 # Имя файла шаблона на AWX-Master (см. ниже)
            dest: /etc/systemd/system/flask_app.service # Куда скопировать на Slave
            owner: root
            group: root
            mode: '0644'
          notify: Reload systemd and Start Flask App # Уведомить handler

        - name: Запустить Nginx
          ansible.builtin.systemd:
            name: nginx
            state: started # Запустить службу
            enabled: yes # Включить в автозапуск при загрузке системы

        - name: Проверить, что сайт запущен и доступен через Nginx
          ansible.builtin.uri:
            url: "http://localhost:{{ nginx_listen_port }}" # URL для проверки (Nginx слушает на этом порту)
            status_code: 200 # Ожидаемый HTTP-статус (200 OK)
            validate_certs: no # Не проверять сертификаты (если используете HTTPS, измените)
          register: website_check # Сохраняем результат
          retries: 10 # Повторить попытку 10 раз
          delay: 5 # С задержкой в 5 секунд между попытками (даем время приложению запуститься)
          until: website_check.status == 200 # Продолжать, пока статус не станет 200

        - name: Отобразить результат финальной проверки
          ansible.builtin.debug:
            msg: "🥳 Сайт успешно запущен и доступен по адресу http://{{ ansible_host }}:{{ nginx_listen_port }}/"
          when: website_check.status == 200

  handlers: # Специальные задачи, которые запускаются только по уведомлению (notify)
    - name: Restart Nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted

    - name: Reload systemd and Start Flask App
      ansible.builtin.systemd:
        daemon_reload: yes # Перезагрузить конфигурацию systemd
      - ansible.builtin.systemd:
          name: flask_app # Название нашей службы
          state: started # Запустить службу
          enabled: yes # Включить в автозапуск
