version: '3.8' # Версия синтаксиса Docker Compose

services:
  web: # Имя вашего сервиса (можно назвать как угодно, например 'flask-app')
    build: . # Указывает Docker Compose, что нужно собрать образ из текущей директории (где Dockerfile)
    ports:
      - "5000:5000" # Пробрасывает порт 5000 с хост-машины на порт 5000 контейнера.
                   # Вы сможете получить доступ к приложению по адресу http://<IP_SLAVE_VM>:5000
    volumes:
      - .:/app # Монтирует текущую директорию хоста (где находится ваш код) в /app внутри контейнера.
               # Это позволяет изменять код на хосте, и изменения будут видны в контейнере без пересборки образа (для разработки).
               # В продакшене эту строку можно убрать, чтобы код был "запечен" в образ.
    environment:
      FLASK_APP: app.py # <--- ОЧЕНЬ ВАЖНО: Убедитесь, что это имя вашего главного файла Flask-приложения!
      FLASK_ENV: production # Установка окружения Flask в production
    restart: always # Автоматически перезапускать контейнер, если он падает
